BEGIN;

CREATE TABLE users(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	email CHARACTER VARYING(150) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE candidates(
	user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	first_name CHARACTER VARYING(50) NOT NULL,
	last_name CHARACTER VARYING(50) NOT NULL,
	identity_number CHARACTER(11) NOT NULL,
	date_of_birth DATE NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY (user_id),
	CONSTRAINT fk_candidates_users FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT uk_candidates_identity_number UNIQUE (identity_number)
);

CREATE TABLE employers(
	user_id INTEGER NOT NULL,
	company_name CHARACTER VARYING(150) NOT NULL,
	web_address CHARACTER VARYING(150) NOT NULL,
	phone_number CHARACTER(15) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY (user_id),
	CONSTRAINT fk_employers_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE updated_employers(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	employer_id INTEGER NOT NULL,
	email CHARACTER VARYING(150) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	company_name CHARACTER VARYING(150) NOT NULL,
	web_address CHARACTER VARYING(150) NOT NULL,
	phone_number CHARACTER(15) NOT NULL,
	CONSTRAINT pk_updated_employers PRIMARY KEY (id),
	CONSTRAINT fk_updated_employers_employers FOREIGN KEY (employer_id) REFERENCES employers (user_id)
);

CREATE TABLE job_titles(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	title CHARACTER VARYING(150) NOT NULL,
	CONSTRAINT pk_job_titles PRIMARY KEY (id),
	CONSTRAINT uk_job_titles_title UNIQUE (title)
);


CREATE TABLE job_postings(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	employer_id INTEGER NOT NULL,
	job_title_id INTEGER NOT NULL,
	city_id INTEGER NOT NULL,
	working_time_id INTEGER NOT NULL,
	working_type_id INTEGER NOT NULL,
	job_description CHARACTER VARYING(2300) NOT NULL,
	number_of_open_positions INTEGER NOT NULL,
	salary_min CHARACTER VARYING(50),
	salary_max CHARACTER VARYING(50),
	posting_date TIMESTAMP WITH TIME ZONE NOT NULL,
	closing_date TIMESTAMP WITH TIME ZONE NOT NULL,
	is_active BOOLEAN NOT NULL,
	CONSTRAINT pk_job_postings PRIMARY KEY (id),
	CONSTRAINT fk_job_postings_employers FOREIGN KEY (employer_id) REFERENCES employers (user_id),
	CONSTRAINT fk_job_postings_job_titles FOREIGN KEY (job_title_id) REFERENCES job_titles (id)
);

CREATE TABLE resumes(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	candidate_id INTEGER NOT NULL,
	creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT pk_resumes PRIMARY KEY (id),
	CONSTRAINT fk_resumes_candidates FOREIGN KEY (candidate_id) REFERENCES candidates (user_id)
);

CREATE TABLE educations(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	resume_id INTEGER NOT NULL,
	name_of_educational_institution CHARACTER VARYING(150) NOT NULL,
	department CHARACTER VARYING(150) NOT NULL,
	degree CHARACTER VARYING(50) NOT NULL,
	starting_date DATE NOT NULL,
	graduation_date DATE,
	CONSTRAINT pk_educations PRIMARY KEY (id),
	CONSTRAINT fk_educations_resumes FOREIGN KEY (resume_id) REFERENCES resumes (id)
);

CREATE TABLE experiences(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	resume_id INTEGER NOT NULL,
	job_title_id INTEGER NOT NULL,
	company_name CHARACTER VARYING(150) NOT NULL,
	starting_date DATE NOT NULL,
	termination_date DATE,
	CONSTRAINT pk_experiences PRIMARY KEY (id),
	CONSTRAINT fk_experiences_resumes FOREIGN KEY (resume_id) REFERENCES resumes (id),
	CONSTRAINT fk_experiences_job_titles FOREIGN KEY (job_title_id) REFERENCES job_titles (id)
);

CREATE TABLE languages(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	language CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT pk_languages PRIMARY KEY (id),
	CONSTRAINT uk_languages_language UNIQUE (language)
);

CREATE TABLE skills(
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	resume_id INTEGER NOT NULL,
	skill CHARACTER VARYING(150) NOT NULL,
	CONSTRAINT pk_skills PRIMARY KEY (id),
	CONSTRAINT fk_skills_resumes FOREIGN KEY (resume_id) REFERENCES resumes (id)
);

INSERT INTO users VALUES (DEFAULT, 'elifintizam@gmail.com', 1234567);
INSERT INTO users VALUES (DEFAULT, 'busrauylas01@gmail.com', 1234567);

INSERT INTO candidates VALUES (1, 'Elif', 'İntizamoğlu', 02222222222, '1999-01-01');
INSERT INTO candidates VALUES (2, 'Necibe Büşra', 'Uylaş', 03333333333, '1998-02-02');

INSERT INTO employers VALUES (1, 'Progress Software', 'progresssoftware.com', 4444444);
INSERT INTO employers VALUES (2, 'Reusable', 'reusable.com', 4444444);

INSERT INTO job_titles VALUES (DEFAULT, 'Software Developer');
INSERT INTO job_titles VALUES (DEFAULT, 'Software Engineer');
INSERT INTO job_titles VALUES (DEFAULT, 'Front-end Developer');
INSERT INTO job_titles VALUES (DEFAULT, 'Data Science Engineer');
INSERT INTO job_titles VALUES (DEFAULT, 'Machine Learning Engineer');
INSERT INTO job_titles VALUES (DEFAULT, 'Unity Developer');
INSERT INTO job_titles VALUES (DEFAULT, 'UIUX Designer');
INSERT INTO job_titles VALUES (DEFAULT, 'Database Administrator');
INSERT INTO job_titles VALUES (DEFAULT, 'Game Developer');

INSERT INTO resumes VALUES (DEFAULT, 1, '2021-07-02T000001.010101');
INSERT INTO resumes VALUES (DEFAULT, 2, '2021-07-03T000001.010101');

INSERT INTO educations VALUES (DEFAULT, 1, 'Çukurova Üniversitesi', 'Bilgisayar Mühendisliği', 'Lisans', '13-08-2017', '14-06-2022');
INSERT INTO educations VALUES (DEFAULT, 2, 'Çukurova Üniversitesi', 'Bilgisayar Mühendisliği', 'Lisans', '18-08-2017', '14-06-2022');

INSERT INTO experiences VALUES (DEFAULT, 1, 2, 'Extra Documentation Co', '09-09-2005', '07-07-2010');
INSERT INTO experiences VALUES (DEFAULT, 1, 2, 'Onset Software', '11-11-2010', null);
INSERT INTO experiences VALUES (DEFAULT, 2, 9, 'Sustain Spot', '09-09-2006', '07-07-2011');

INSERT INTO languages VALUES (DEFAULT, 'Türkçe');
INSERT INTO languages VALUES (DEFAULT, 'İngilizce');
INSERT INTO languages VALUES (DEFAULT, 'Fransızca');

INSERT INTO skills VALUES (DEFAULT, 2, 'Oracle');
INSERT INTO skills VALUES (DEFAULT, 2, 'MySQL');
INSERT INTO skills VALUES (DEFAULT, 2, 'PostgreSQL');
INSERT INTO skills VALUES (DEFAULT, 1, '.NET');
INSERT INTO skills VALUES (DEFAULT, 1, 'C++');
INSERT INTO skills VALUES (DEFAULT, 1, 'C');

END;
