"""empty message

Revision ID: 13418ef8196b
Revises: 5d465c987cf8
Create Date: 2022-05-20 15:12:37.529102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13418ef8196b'
down_revision = '5d465c987cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
