"""empty message

Revision ID: 4150d3ceb9ac
Revises: 
Create Date: 2022-05-29 11:47:15.155014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4150d3ceb9ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identity_number', sa.String(length=11), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_number')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('job_description', sa.String(length=2300), nullable=False),
    sa.Column('salary_min', sa.String(length=50), nullable=True),
    sa.Column('salary_max', sa.String(length=50), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('skills', sa.String(length=300), nullable=False),
    sa.Column('languages', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name_of_educational_institution', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiences')
    op.drop_table('educations')
    op.drop_table('resumes')
    op.drop_table('job_postings')
    op.drop_table('candidates')
    # ### end Alembic commands ###
