"""empty message

Revision ID: b7c32fe2be67
Revises: dc7a1225abb0
Create Date: 2022-05-18 00:46:11.210665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c32fe2be67'
down_revision = 'dc7a1225abb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('identity_number', sa.String(length=11), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name_of_educational_institution', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('web_address', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'job_title_id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.String(length=2300), nullable=False),
    sa.Column('salary_min', sa.String(length=50), nullable=True),
    sa.Column('salary_max', sa.String(length=50), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('updated_employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('web_address', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('updated_employers')
    op.drop_table('skills')
    op.drop_table('resumes')
    op.drop_table('languages')
    op.drop_table('job_titles')
    op.drop_table('job_postings')
    op.drop_table('experiences')
    op.drop_table('employers')
    op.drop_table('educations')
    op.drop_table('candidates')
    # ### end Alembic commands ###
