"""empty message

Revision ID: e9bf663223e3
Revises: 4150d3ceb9ac
Create Date: 2022-06-10 11:34:37.926111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bf663223e3'
down_revision = '4150d3ceb9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
