"""empty message

Revision ID: f389110b4d9c
Revises: 39e44217cea3
Create Date: 2022-06-10 11:39:23.404768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f389110b4d9c'
down_revision = '39e44217cea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
